-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpu_set_clip is
port (
    arg0_V : IN STD_LOGIC_VECTOR (15 downto 0);
    arg1_V : IN STD_LOGIC_VECTOR (15 downto 0);
    arg2_V : IN STD_LOGIC_VECTOR (15 downto 0);
    arg3_V : IN STD_LOGIC_VECTOR (15 downto 0);
    clip_x_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    clip_x_V_ap_vld : OUT STD_LOGIC;
    clip_y_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    clip_y_V_ap_vld : OUT STD_LOGIC;
    clip_w_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    clip_w_V_ap_vld : OUT STD_LOGIC;
    clip_h_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    clip_h_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of gpu_set_clip is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';



begin



    clip_h_V <= arg3_V;
    clip_h_V_ap_vld <= ap_const_logic_1;
    clip_w_V <= arg2_V;
    clip_w_V_ap_vld <= ap_const_logic_1;
    clip_x_V <= arg0_V;
    clip_x_V_ap_vld <= ap_const_logic_1;
    clip_y_V <= arg1_V;
    clip_y_V_ap_vld <= ap_const_logic_1;
end behav;
