// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xgpu.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XGpu_CfgInitialize(XGpu *InstancePtr, XGpu_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XGpu_Start(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL) & 0x80;
    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XGpu_IsDone(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XGpu_IsIdle(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XGpu_IsReady(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XGpu_EnableAutoRestart(XGpu *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XGpu_DisableAutoRestart(XGpu *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_AP_CTRL, 0);
}

void XGpu_Set_frameBuffer_V(XGpu *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_FRAMEBUFFER_V_DATA, Data);
}

u32 XGpu_Get_frameBuffer_V(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_FRAMEBUFFER_V_DATA);
    return Data;
}

void XGpu_Set_status_V(XGpu *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_STATUS_V_DATA, Data);
}

u32 XGpu_Get_status_V(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_STATUS_V_DATA);
    return Data;
}

void XGpu_Set_cl_V(XGpu *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_CL_V_DATA, Data);
}

u32 XGpu_Get_cl_V(XGpu *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_CL_V_DATA);
    return Data;
}

void XGpu_InterruptGlobalEnable(XGpu *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_GIE, 1);
}

void XGpu_InterruptGlobalDisable(XGpu *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_GIE, 0);
}

void XGpu_InterruptEnable(XGpu *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_IER);
    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_IER, Register | Mask);
}

void XGpu_InterruptDisable(XGpu *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_IER);
    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_IER, Register & (~Mask));
}

void XGpu_InterruptClear(XGpu *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGpu_WriteReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_ISR, Mask);
}

u32 XGpu_InterruptGetEnabled(XGpu *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_IER);
}

u32 XGpu_InterruptGetStatus(XGpu *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGpu_ReadReg(InstancePtr->Control_BaseAddress, XGPU_CONTROL_ADDR_ISR);
}

